[package]
name = "euler"
version = "0.1.0"
authors = ["Samuel Cormier-Iijima <sciyoshi@gmail.com>"]

[dependencies]
primal = "*"
roaring = "*"
num = "*"
mod_pow = { git = "https://github.com/kunerd/mod_pow" }